using System;using System.Collections.Generic;using System.Diagnostics;using System.Runtime.InteropServices;
namespace VicarShotgunKeyboard.Services;
public enum KeyCategory{Letter,Number,Symbol,Space,Enter,Backspace,Tab,Arrow,Function,Ctrl,Alt,Shift,Windows}
public sealed class KeyPressedEventArgs:EventArgs{public uint VirtualKey{get;init;}public KeyCategory Category{get;init;}public bool IsDown{get;init;}}
public sealed class KeyboardHookService
{
 const int WH_KEYBOARD_LL=13,WM_KEYDOWN=0x100,WM_KEYUP=0x101,WM_SYSKEYDOWN=0x104,WM_SYSKEYUP=0x105;readonly AppLogger logger;IntPtr hook;Native.LowLevelKeyboardProc? proc;readonly HashSet<uint> down=new();readonly Dictionary<string,bool> filters=new();
 public event EventHandler<KeyPressedEventArgs>? KeyPressed;public bool IgnoreRepeat{get;set;}=true;public bool PlayOnRelease{get;set;}
 public KeyboardHookService(AppLogger l)=>logger=l;public void ApplyFilters(Dictionary<string,bool> f){filters.Clear();foreach(var x in f)filters[x.Key]=x.Value;}
 public void Start(){if(hook!=IntPtr.Zero)return;proc=Callback;using var p=Process.GetCurrentProcess();using var m=p.MainModule!;hook=Native.SetWindowsHookEx(WH_KEYBOARD_LL,proc,Native.GetModuleHandle(m.ModuleName),0);if(hook==IntPtr.Zero)logger.Error("Keyboard hook failed: "+Marshal.GetLastWin32Error());}
 public void Stop(){if(hook!=IntPtr.Zero){Native.UnhookWindowsHookEx(hook);hook=IntPtr.Zero;}lock(down)down.Clear();}
 IntPtr Callback(int n,IntPtr w,IntPtr l){if(n>=0){var d=Marshal.PtrToStructure<Native.KBD>(l);bool isDown=w==(IntPtr)WM_KEYDOWN||w==(IntPtr)WM_SYSKEYDOWN;bool isUp=w==(IntPtr)WM_KEYUP||w==(IntPtr)WM_SYSKEYUP;if(isDown||isUp){var c=Classify(d.vk);bool repeat=false;lock(down){if(isDown){repeat=down.Contains(d.vk);down.Add(d.vk);}else down.Remove(d.vk);}if(Enabled(c)&&(!IgnoreRepeat||!repeat)&&((isDown&&!PlayOnRelease)||(isUp&&PlayOnRelease)))KeyPressed?.Invoke(this,new(){VirtualKey=d.vk,Category=c,IsDown=isDown});}}return Native.CallNextHookEx(hook,n,w,l);}
 bool Enabled(KeyCategory c)=>c switch{KeyCategory.Letter=>Get("Letters",true),KeyCategory.Number=>Get("Numbers",true),KeyCategory.Symbol=>Get("Symbols",true),KeyCategory.Space=>Get("Space",true),KeyCategory.Enter=>Get("Enter",true),KeyCategory.Backspace=>Get("Backspace",true),KeyCategory.Tab=>Get("Tab",true),KeyCategory.Arrow=>Get("ArrowKeys",false),KeyCategory.Function=>Get("FunctionKeys",false),KeyCategory.Ctrl=>Get("Ctrl",false),KeyCategory.Alt=>Get("Alt",false),KeyCategory.Shift=>Get("Shift",false),KeyCategory.Windows=>Get("WindowsKey",false),_=>false};
 bool Get(string k,bool d)=>filters.TryGetValue(k,out var v)?v:d;
 static KeyCategory Classify(uint v)=>v switch{>=0x41 and <=0x5A=>KeyCategory.Letter,>=0x30 and <=0x39 or >=0x60 and <=0x69=>KeyCategory.Number,0x20=>KeyCategory.Space,0x0D=>KeyCategory.Enter,0x08=>KeyCategory.Backspace,0x09=>KeyCategory.Tab,0x25 or 0x26 or 0x27 or 0x28=>KeyCategory.Arrow,>=0x70 and <=0x7B=>KeyCategory.Function,0x10 or 0xA0 or 0xA1=>KeyCategory.Shift,0x11 or 0xA2 or 0xA3=>KeyCategory.Ctrl,0x12 or 0xA4 or 0xA5=>KeyCategory.Alt,0x5B or 0x5C=>KeyCategory.Windows,_=>KeyCategory.Symbol};
 static class Native{[StructLayout(LayoutKind.Sequential)]public struct KBD{public uint vk,scan,flags,time;public UIntPtr extra;}public delegate IntPtr LowLevelKeyboardProc(int n,IntPtr w,IntPtr l);[DllImport("user32.dll",SetLastError=true)]public static extern IntPtr SetWindowsHookEx(int id,LowLevelKeyboardProc p,IntPtr m,uint t);[DllImport("user32.dll")]public static extern bool UnhookWindowsHookEx(IntPtr h);[DllImport("user32.dll")]public static extern IntPtr CallNextHookEx(IntPtr h,int n,IntPtr w,IntPtr l);[DllImport("kernel32.dll",CharSet=CharSet.Unicode)]public static extern IntPtr GetModuleHandle(string? n);}
}